### PR TITLE
Implement whitespace cleanup for non-insert changes

### PR DESCRIPTION
**Pull request by thirtythreeforty**
See #2 for the suggestion.

### CODE REVIEW

**Comment by thirtythreeforty** [comment]
@xileF1337, could you give this branch a whirl?  There's still some edge cases unfortunately... The main one I run into is that the entire file is considered to have "changed" when running `:e!` (force reload from disk), and the plugin strips the entire file :expressionless:.

I'm going to continue to think about how to decide that the user made a "normal" mode change... it's not as easy as "ignore all Ex commands," because most Ex operations are user-performed.

**Comment by thirtythreeforty** [comment]
This is a list of edge cases/bugs that I find, in no particular order.
- [ ] Deleting lines at the end of the file causes an error.
- [ ] Reloading the file (`:e`) causes the whole thing to get stripped.

**Comment by xileF1337** [comment]
Thanks for the update, George! I was out of office for a week and checked out your patch just now, and it seems to work well. I will report back if I find any bugs or glitches.

**Comment by thirtythreeforty** [comment]
OK, I've fixed everything I've noticed.  I'm going to dogfood this branch for a few more days then merge it into mainline!

**Comment by xileF1337** [comment]
Thanks again for your efforts!

**Comment by thirtythreeforty** [comment]
Merged.  Seems stable enough.  Thanks for using!

**Pull request merged**
